function model = load_model(metabolic_model, NGAM)
% Load a genome scale model for the selected organism.
% Options:
% metabolic_model: 'iCG760_Minato_MtbYM',
%                  'iSM810_Minato_MtbYM', 'sMtb_Minato_MtbYM',
%                  'GSMN_TB_1.1_Minato_MtbYM';
%
% Author: Victor Lopez, July 9, 2019.

%% non-growth associated maintenance to 0.1 mmol gdw-1 h-1 as suggested by Rienksma et al., 2014
%NGAM = 1;

%% MODEL PATH

    VASHISHT_MODEL = 'model/iOSDD890.mat';
    GARAY_MODEL = 'model/iCG760_grRuleCorrected.mat'; 
    MA_MODEL = 'model/iSM810_grRuleCorrected.mat';
    LOFTHOUSE_MODEL = 'model/GSMN_TB1.1_grRuleCorrected.mat';
    XAVIER_MODEL = 'model/iNJ661v_modified.mat';
    RIENKSMA_2014 = 'model/sMtb_grRuleCorrected.mat';
    RIENKSMA_2018 = 'model/sMtb2018_EX.mat';
    KAVVAS_MODEL = 'model/iEK1011_xlsx.mat';
    KAVVAS_2_0 = 'model/iEK1011_2.0.mat';
    sMTB_2_0 = 'model/sMtb2.0_tics_v13_1.mat';
    
%% MEDIUM PATH

    MA_MEDIUM = 'medium/ExchangeRxns_MA2015.mat';
    LOFTHOUSE_MEDIUM = 'medium/ExchangeRxns_MA2015.mat';   

%% CHOICES    
    
switch metabolic_model
    
             case 'iCG760_Minato_MtbYM'
                    
                    load(GARAY_MODEL);
                    model = iCG760;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    model = changeRxnBounds(model,'R129',NGAM,'b'); % Mainteinence was fixt to 1 mmol/gDW/h
                    Medium_Minato_MtbYM={'EX_ASN(e)','EX_PI(e)','EX_H(e)','EX_FE3(e)',...
                                              'EX_O2(e)','EX_NH3(e)','EX_SLF(e)','EX_CIT(e)','EX_GL(e)','EX_ETH(e)',...
											  'EX_9_OCTADECENOATE(e)','EX_AC(e)','EX_ALA(e)','EX_ARG(e)',...
											  'EX_ASN(e)','EX_ASP(e)','EX_BIOTIN(e)','EX_CO_II(e)','EX_CYS(e)','EX_DALA(e)',...
											  'EX_DAPIM(e)','EX_GLC(e)','EX_GLN(e)','EX_GLU(e)','EX_GLY(e)','EX_HIS(e)',...
											  'EX_HYXN(e)','EX_ILE(e)','EX_INS(e)','EX_LEU(e)','EX_LYS(e)','EX_MET(e)',...
											  'EX_NAC(e)','EX_ORN(e)','EX_PHE(e)','EX_PRO(e)','EX_PYR(e)','EX_RIB(e)',...
											  'EX_SER(e)','EX_THR(e)','EX_TRE(e)','EX_TRP(e)','EX_TYR(e)','EX_VAL(e)'};

                    Minato_MtbYM_data = [ 1, 1, 1000, 5, 20, 10, 1000, 1, 1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...
					                      1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                    
    
            case 'iSM810_Minato_MtbYM'
                               
                    load (MA_MODEL);
                    model = iSM810;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000; 
                    load (MA_MEDIUM);
                    model = changeRxnBounds(model,ExchangeRxns,0,'u');
                    model = changeRxnBounds(model,'R129',NGAM,'b'); % Maintainance was fix to 1 mmol/gDWH
                    Medium_Minato_MtbYM = { 'R800', 'R804', 'R866', 'R822', 'R838', 'R841', 'R882', 'R924', 'R858',...
                                            'R808','R815','R816','R820','R821','R822','R823','R826','R827','R828',...
											'R829','R830','R831','R832','R833','R834','R835','R837','R839','R840',...
											'R842','R843','R844','R848','R849','R850','R856','R863','R864','R866',...
											'R868','R869','R870','R871','R872','R874','R875','R876','R877','R878',...
											'R881','R883','R884','R885','R886','R887','R891','R892','R893','R894',...
											'R897','R898','R902','R903','R918','R925','R926'};                   
                    Minato_MtbYM_data = [ 10, 20, 1, 1, 1, 1000, 1, 1, 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...
					                      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM, Minato_MtbYM_data,'u');
                    
                   
              case 'sMtb_Minato_MtbYM'
            
                   load(RIENKSMA_2014);
                   model = sMtb;
                   model.lb(model.lb < 0) = -1000;
                   model.ub(model.ub > 1) = 1000;
                   exchangeRxns  = model.rxns(findExcRxns(model)); 
                   model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                   Medium_Minato_MtbYM={'EX_ASN[e]','EX_CL[e]','EX_PI[e]','EX_H[e]','EX_K[e]',...
                                            'EX_NA[e]','EX_ZN[e]','EX_MG[e]', 'EX_CA[e]','EX_FE2[e]',...
                                            'EX_FE3[e]','EX_H2O[e]','EX_O2[e]','EX_NH3[e]','EX_SLF[e]',...
                                            'EX_CIT[e]','EX_GL[e]', 'EX_ETH[e]'...
											'EX_9OCTADECENOATE[e]','EX_AC[e]','EX_ALA[e]','EX_ARG[e]',...
											'EX_ASN[e]','EX_ASP[e]','EX_BIOTIN[e]',...
											'EX_CADA[e]','EX_CA[e]','EX_CYS[e]','EX_DIN[e]',...
											'EX_GLC[e]','EX_GLN[e]','EX_GLU[e]','EX_GLY[e]','EX_HIS[e]','EX_HYXN[e]'...
											,'EX_ILE[e]','EX_INS[e]','EX_LEU[e]','EX_LYS[e]','EX_MET[e]','EX_NAC[e]',...
											'EX_ORN[e]','EX_PABA[e]','EX_PHE[e]','EX_PHOSPHATIDYLCHOLINE[e]','EX_PI[e]'...
											,'EX_PNTO[e]','EX_PRO[e]','EX_PYRI[e]','EX_PYR[e]','EX_RIBFLAV[e]','EX_RIB[e]'...
											,'EX_SER[e]','EX_THR[e]','EX_TRE[e]','EX_TRP[e]','EX_TYR[e]','EX_VAL[e]'};  
                   Minato_MtbYM_data = [ 1, 1000, 1, 1000, 1000, 1000, 1000, 1000, 1000, 5, 5, 1000, 20, 10, 1000, 1, 1, 1,...
										1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                   model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                   model = changeRxnBounds(model,'Maintenance',NGAM,'b'); % Maintenance reaction was fix to 1 mmol/gDW/h.
                     
                     
              case 'GSMN_TB_1.1_Minato_MtbYM'
                    
                    load(LOFTHOUSE_MODEL);
                    load(LOFTHOUSE_MEDIUM);
                    model = GSMN_TB1_1;
                    model.ub(model.ub > 1) = 1000;
                    model = changeRxnBounds(model,ExchangeRxns,0,'u');
                    model = changeRxnBounds(model,'R129',NGAM,'b'); % maintaince reaction was fix to 1 mmol/gDW/h
                    Medium_Minato_MtbYM = { 'R800', 'R804', 'R866', 'R822', 'R838', 'R841', 'R882', 'R924', 'R858',...
											'R808','R815','R816','R820','R821','R822','R823','R826','R827','R828',...
											'R829','R830','R831','R832','R833','R834','R835','R837','R839','R840',...
											'R842','R843','R844','R848','R849','R850','R856','R863','R864','R866',...
											'R868','R869','R870','R871','R872','R874','R875','R876','R877','R878',...
											'R881','R883','R884','R885','R886','R887','R891','R892','R893','R894',...
											'R897','R898','R902','R903','R918','R925','R926'};                   
                    Minato_MtbYM_data = [ 10, 20, 1, 1, 1, 1000, 1, 1, 1,...
                                          1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM, Minato_MtbYM_data,'u');
                    
              case 'iOSDD890_Minato_MtbYM' %EX_etoh not in model.
                    
                    load(VASHISHT_MODEL);
                    model = iOSDD890;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    Medium_Minato_MtbYM={'EX_h(e)', 'EX_h2o(e)', 'EX_o2(e)', 'EX_asn_L(e)', 'EX_nh4(e)' ,...
                                                'EX_cit(e)', 'EX_ca2(e)', 'EX_cl(e)', 'EX_mg2(e)',...
                                                'EX_so4(e)', 'EX_fe3(e)', 'EX_pi(e)', 'EX_glyc(e)'...
										 'EX_ala_L(e)','EX_arg_L(e)','EX_asn_L(e)','EX_asp_L(e)','EX_cobalt2(e)',...
										 'EX_glc(e)','EX_glu_L(e)','EX_gly(e)','EX_ile_L(e)','EX_leu_L(e)',...
										 'EX_lys_L(e)','EX_met_L(e)','EX_ocdca(e)','EX_orn(e)','EX_pro_L(e)',...
										 'EX_pyr(e)','EX_rib_D(e)','EX_ser_L(e)','EX_thr_L(e)','EX_tre(e)',...
										 'EX_trp_L(e)','EX_tyr_L(e)','EX_val_L(e)','EX_ac(e)','EX_4abz(e)'};              
                    Minato_MtbYM_data = [ 1000, 1000, 20, 1, 10, 1, 1000, 1000, 1000, 1000, 5, 1, 1,...
                                          1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                    model = changeRxnBounds(model,'ATPS1',1,'b'); % maintaince reaction was fix to 1 mmol/gDW/h
                    
               case 'iNJ661v_modified_Minato_MtbYM' % Etoh not in model.
            
                    load(XAVIER_MODEL);
                    model = iNJ661v_modified;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    Medium_Minato_MtbYM={'EX_h(e)', 'EX_h2o(e)', 'EX_o2(e)', 'EX_asn_L(e)', 'EX_nh4(e)' ,...
                                                'EX_cit(e)', 'EX_ca2(e)', 'EX_cl(e)', 'EX_mg2(e)',...
                                                'EX_so4(e)', 'EX_fe3(e)','EX_fe2(e)', 'EX_pi(e)', 'EX_glyc(e)',...
                                                'EX_k(e)','EX_na1(e)'...
										'EX_ala_L(e)','EX_arg_L(e)','EX_asn_L(e)','EX_asp_L(e)','EX_cobalt2(e)',...
										'EX_glc(e)','EX_glu_L(e)','EX_gly(e)','EX_glyb(e)','EX_his_L(e)','EX_ile_L(e)'...
										'EX_leu_L(e)','EX_lys_L(e)','EX_met_L(e)','EX_ocdca(e)','EX_orn(e)','EX_phe_L(e)',...
										'EX_pro_L(e)','EX_pyr(e)','EX_rib_D(e)','EX_ser_L(e)','EX_thr_L(e)','EX_tre(e)',...
										'EX_trp_L(e)','EX_tyr_L(e)','EX_val_L(e)','EX_btn(e)','EX_pydxn(e)'};              
                    Minato_MtbYM_data = [ 1000, 1000, 20, 1, 10, 1, 1000, 1000, 1000, 1000, 5, 5, 1, 1, 1000, 1000,...
										  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l'); 
                    ADD_iNJ661v = {'EX_xyl_D(e)'};
                    model = changeRxnBounds(model,ADD_iNJ661v,-0.01, 'l');
                    model = changeRxnBounds(model,'ATPS1',NGAM,'b'); % maintaince reaction was fix to 1 mmol/gDW/h
                
                 case 'sMtb2018_Minato_MtbYM'
                  
                    load(RIENKSMA_2018);
                    model = sMtb2018;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    Medium_Minato_MtbYM={'R_EX_ASN[e]','R_EX_CL[e]','R_EX_PI[e]','R_EX_H[e]','R_EX_K[e]','R_EX_NA[e]','R_EX_ZN[e]',...
                                             'R_EX_MG[e]', 'R_EX_CA[e]','R_EX_FE2[e]','R_EX_FE3[e]','R_EX_H2O[e]','R_EX_O2[e]',...
                                             'R_EX_NH3[e]','R_EX_SLF[e]','R_EX_CIT[e]','R_EX_GL[e]', 'R_EX_ETH[e]',...
											'R_EX_9OCTADECENOATE[e]','R_EX_AC[e]','R_EX_ALA[e]','R_EX_ARG[e]',...
											'R_EX_ASN[e]','R_EX_ASP[e]','R_EX_BIOTIN[e]',...
											'R_EX_CADA[e]','R_EX_CA[e]','R_EX_COB12[e]','R_EX_CYS[e]','R_EX_DIN[e]',...
											'R_EX_GLC[e]','R_EX_GLN[e]','R_EX_GLU[e]','R_EX_GLY[e]','R_EX_HIS[e]','R_EX_HYXN[e]'...
											,'R_EX_ILE[e]','R_EX_INS[e]','R_EX_LEU[e]','R_EX_LYS[e]','R_EX_MET[e]','R_EX_NAC[e]',...
											'R_EX_ORN[e]','R_EX_PABA[e]','R_EX_PHE[e]','R_EX_PHOSPHATIDYLCHOLINE[e]','R_EX_PI[e]'...
											,'R_EX_PNTO[e]','R_EX_PRO[e]','R_EX_PYRI[e]','R_EX_PYR[e]','R_EX_RIBFLAV[e]','R_EX_RIB[e]'...
											,'R_EX_SER[e]','R_EX_THR[e]','R_EX_TRE[e]','R_EX_TRP[e]','R_EX_TYR[e]','R_EX_VAL[e]'};  
                    Minato_MtbYM_data = [ 1, 1000, 1, 1000, 1000, 1000, 1000, 1000, 1000, 5, 5, 1000, 20, 10, 1000, 1, 1, 1,...
										  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                    model = changeRxnBounds(model,'R_Maintenance',NGAM,'b'); % Maintenance reaction was fix to 1 mmol/gDW/h.
               
                case 'iEK1011_Minato_MtbYM'
                 
                    load(KAVVAS_MODEL);
                    model = iEK1011;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    Medium_Minato_MtbYM ={'EX_h_e', 'EX_h2o_e', 'EX_o2_e', 'EX_asn__L_e', 'EX_nh4_e' ,...
                                                'EX_cit_e', 'EX_etoh_e', 'EX_ca2_e', 'EX_cl_e', 'EX_mg2_e',...
                                                'EX_so4_e', 'EX_fe3_e', 'EX_pi_e', 'EX_glyc_e',...
												'EX_4abz_e','EX_ac_e','EX_adocbl_e','EX_ala__L_e','EX_arg__L_e',...
												'EX_asn__L_e','EX_asp__L_e','EX_btn_e','EX_cobalt2_e','EX_glc__D_e',...
												'EX_gln__L_e','EX_glu__L_e','EX_gly_e','EX_his__L_e','EX_ile__L_e',...
												'EX_leu__L_e','EX_lys__L_e','EX_met__L_e','EX_ocdca_e','EX_ocdcea_e',...
												'EX_orn_e','EX_phe__L_e','EX_pheme_e','EX_pro__L_e','EX_pydxn_e',...
												'EX_pyr_e','EX_rib__D_e','EX_ser__D_e','EX_ser__L_e','EX_thr__L_e',...
												'EX_tre_e','EX_trp__L_e','EX_tyr__L_e','EX_val__L_e'};              
                    Minato_MtbYM_data = [ 1000, 1000, 20, 1, 10, 1, 1, 1000, 1000, 1000, 1000, 5, 1, 1,...
                                         1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                    model = changeRxnBounds(model,'ATPM',NGAM,'b'); % Maintenance reaction was fix to 1 mmol/gDW/h.

                 case 'iEK1011_2.0_Minato_MtbYM'
                 
                    load(KAVVAS_2_0);
                    model = iEK1011_2_0;
                    model.lb(model.lb < 0) = -1000;
                    model.ub(model.ub > 1) = 1000;
                    exchangeRxns  = model.rxns(findExcRxns(model)); 
                    model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                    Medium_Minato_MtbYM ={'EX_h_e', 'EX_h2o_e', 'EX_o2_e', 'EX_asn__L_e', 'EX_nh4_e' ,...
                                                'EX_cit_e', 'EX_etoh_e', 'EX_ca2_e', 'EX_cl_e', 'EX_mg2_e',...
                                                'EX_so4_e', 'EX_fe3_e', 'EX_pi_e', 'EX_glyc_e',...
												'EX_4abz_e','EX_ac_e','EX_adocbl_e','EX_ala__L_e','EX_arg__L_e',...
												'EX_asn__L_e','EX_asp__L_e','EX_btn_e','EX_cobalt2_e','EX_glc__D_e',...
												'EX_gln__L_e','EX_glu__L_e','EX_gly_e','EX_his__L_e','EX_ile__L_e',...
												'EX_leu__L_e','EX_lys__L_e','EX_met__L_e','EX_ocdca_e','EX_ocdcea_e',...
												'EX_orn_e','EX_phe__L_e','EX_pheme_e','EX_pro__L_e','EX_pydxn_e',...
												'EX_pyr_e','EX_rib__D_e','EX_ser__D_e','EX_ser__L_e','EX_thr__L_e',...
												'EX_tre_e','EX_trp__L_e','EX_tyr__L_e','EX_val__L_e'};              
                    Minato_MtbYM_data = [ 1000, 1000, 20, 1, 10, 1, 1, 1000, 1000, 1000, 1000, 5, 1, 1,...
										1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                    model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                    model = changeRxnBounds(model,'ATPM',NGAM,'b'); % Maintenance reaction was fix to 1 mmol/gDW/h.
    
                 case 'sMtb_2.0_Minato_MtbYM'
            
                   load(sMTB_2_0);
                   model = sMtb2_0_tics_v13_1;
                   model.lb(model.lb < 0) = -1000;
                   model.ub(model.ub > 1) = 1000;
                   exchangeRxns  = model.rxns(findExcRxns(model)); 
                   model = changeRxnBounds(model,exchangeRxns,0,'l'); 
                   Medium_Minato_MtbYM={'EX_ASN[e]','EX_CL[e]','EX_PI[e]','EX_H[e]','EX_K[e]',...
                                            'EX_NA[e]','EX_ZN[e]','EX_MG[e]', 'EX_CA[e]','EX_FE2[e]',...
                                            'EX_FE3[e]','EX_H2O[e]','EX_O2[e]','EX_NH3[e]','EX_SLF[e]',...
                                            'EX_CIT[e]','EX_GL[e]', 'EX_ETH[e]',...
											'EX_9OCTADECENOATE[e]','EX_AC[e]','EX_ALA[e]','EX_ARG[e]',...
											'EX_ASN[e]','EX_ASP[e]','EX_BIOTINSO[e]','EX_BIOTIN[e]',...
											'EX_CADA[e]','EX_CA[e]','EX_COB12[e]','EX_CYS[e]','EX_DIN[e]',...
											'EX_GLC[e]','EX_GLN[e]','EX_GLU[e]','EX_GLY[e]','EX_HIS[e]','EX_HYXN[e]'...
											,'EX_ILE[e]','EX_INS[e]','EX_LEU[e]','EX_LYS[e]','EX_MET[e]','EX_NAC[e]',...
											'EX_ORN[e]','EX_PABA[e]','EX_PHE[e]','EX_PHOSPHATIDYLCHOLINE[e]','EX_PI[e]'...
											,'EX_PNTO[e]','EX_PRO[e]','EX_PYRI[e]','EX_PYR[e]','EX_RIBFLAV[e]','EX_RIB[e]'...
											,'EX_SER[e]','EX_THR[e]','EX_TRE[e]','EX_TRP[e]','EX_TYR[e]','EX_VAL[e]'};  
                   Minato_MtbYM_data = [ 1, 1000, 1, 1000, 1000, 1000, 1000, 1000, 1000, 5, 5, 1000, 20, 10, 1000, 1, 1, 1,...
										1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];
                   model = changeRxnBounds(model,Medium_Minato_MtbYM,-Minato_MtbYM_data,'l');
                   model = changeRxnBounds(model,'Maintenance',NGAM,'b'); % Maintenance reaction was fix to 1 mmol/gDW/h.
                     
                    
                    
end
              
              
end